name: WLV-AI
channels:
  - defaults
dependencies:
  - jupyter
  - numpy=1.26.4
  - pytorch
  - matplotlib
  - seaborn
  - python=3.10
  - scipy
  - pandas
  - ipykernel
  - scikit-learn
prefix: /home/dev-algo/anaconda3/envs/WLV-AI